# Generated by Django 4.1 on 2022-08-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('link', models.SlugField(max_length=600, verbose_name='ссылка')),
                ('description', models.TextField(max_length=600, verbose_name='описание')),
                ('tag', models.CharField(max_length=40, verbose_name='заголовок')),
            ],
        ),
    ]
